#!/usr/bin/env node
/**
 * Bundle @visteras/fonts for static Vector (browser ESM, JSON inlined).
 */
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(root, '../..');
const outfile = path.join(repoRoot, 'apps/vector/lib/visteras-fonts.js');
const entry = path.join(root, 'src/index.js');

fs.mkdirSync(path.dirname(outfile), { recursive: true });

const result = spawnSync(
	'npx',
	['--yes', 'esbuild', entry, '--bundle', '--format=esm', '--outfile=' + outfile, '--platform=browser', '--target=es2020'],
	{ stdio: 'inherit', cwd: root, shell: false },
);

if (result.status !== 0) {
	console.error('esbuild failed; writing a hand-rolled ESM fallback is not automatic.');
	process.exit(result.status || 1);
}

const banner = `/* @visteras/fonts — generated by packages/fonts/scripts/build-vector.mjs — do not edit by hand */\n`;
const body = fs.readFileSync(outfile, 'utf8');
if (!body.startsWith('/* @visteras/fonts')) {
	fs.writeFileSync(outfile, banner + body);
}
console.log('Wrote', outfile);
